### ISSUE TITLE
Phase 1 Description

### ISSUE THREAD

**Issue by MiWeiss** [eccv22-ood-workshop/ROBIN-dataset#20]
Thanks for organizing this challenge!

The README lists the following:

>  we will ask each team to provide a description of their developing environment at the end of Phase-1

Could you provide a little more detail as to what type of description is expected? A short paper? An abstract? Just some notes?

**Comment by DTennant** [comment]
Hi,

Thanks for your interest in our challenge.
For the description at the end of Phase-1, a document of the libraries used is needed as we would change to code submission in Phase-2. The document can be in the form of a requirements.txt or a Dockerfile.

**Comment by MiWeiss** [comment]
Thank you! That answers my question
