### ISSUE TITLE
Some descriptions of competition are contradictory

### ISSUE THREAD

**Issue by wjm-wjm** [eccv22-ood-workshop/ROBIN-dataset#22]
The description in the Evaluation says:
![7db2b5b660ef1358eea4791936f5f89](https://user-images.githubusercontent.com/53390698/185881889-de399c05-78d5-4e7a-acc7-08767adfad4a.png)
while the description in the Changes says:
![c2bf50cc6217b81f716add1143f73ce](https://user-images.githubusercontent.com/53390698/185882070-287af524-9e76-4044-a905-abd9efcaba07.png) 
I'm confused that whether ImageNet-1k dataset and pertrained model of ImageNet-1k can be used in the training process?

**Comment by DTennant** [comment]
Hi,

ImageNet-1k and ImageNet-1k pretrained models can be used for training

**Comment by wjm-wjm** [comment]
OK, thanks a lot！
