### ISSUE TITLE
Clarifications on Image Classification Track

### ISSUE THREAD

**Issue by CJaehyun** [eccv22-ood-workshop/ROBIN-dataset#28]
Hi,

Thank you for hosting such a workshop on OOD.

I have some general questions regarding the image classification track.

1) I thought the model for training / testing was restricted to ResNet50 only, but I can't find this restriction now. Did the rules change?

2) For ensemble training, are we allowed to use models other than ResNet50?

3) For the description at the end of Phase 1, how are we supposed to upload the description file?

Thank you in advance.

**Comment by DTennant** [comment]
Hi:

Regarding your questions:
1. We do not have the restriction of ResNet50 only, our restrictions are,
that the model can only be trained on ImageNet1k and/or our provided
training set, and also the IID test performance should not exceed a
predefined threshold.
2. Yes, you can use any model for ensembling.
3. We will send out emails to all teams on CodaLab at the end of phase 1
and ask for the description file.



CJaehyun ***@***.***> 于2022年9月16日周五 00:44写道：
