### ISSUE TITLE
The categories of the detection track

### ISSUE THREAD

**Issue by zhengye1995** [eccv22-ood-workshop/ROBIN-dataset#4]
Thanks for your great benchmark for ood evaluation.

After I unzip the dataset for detection track, I found that there are 20 categories in the annotation of the dataset instead of the 10 in the workshop's homepage. What are the actual categories used for detection track? If there are only 10 categories, are images containing other categories used as backgrounds or I should drop them?

**Comment by DTennant** [comment]
Hi, we will update the repo with more information ASAP.
For now, we are still preparing the data, please stay tuned.
