### ISSUE TITLE
Low Quality Validation Set

### ISSUE THREAD

**Issue by JeremyCJM** [eccv22-ood-workshop/ROBIN-dataset#9]
Hi all, 

I compared your new classification dataset (v1.0) with the previous version recently. The quality of the current validation set is pretty lower -- and there are many unrelated objects appearing in the images, e.g. a "car" image has a bike in the foreground and a car in the background, a "car" image with a very large airplane and a very small car. I believe those images are not appropriate to evaluate the new OOD issues proposed in your paper. 

I am wondering if there is any mistake in the data collection that you may not notice? And would this v1.0 be the final dataset we use for the challenge?

Thanks,
Jeremy

**Comment by mmmmimic** [comment]
Hi Jeremy, 

Could you let me know if you have addressed the problem? I think I have the same question with you:)

Thanks!
Manxi

**Comment by JeremyCJM** [comment]
It seems that v1.0 is for all three tasks, and the author provided the processing scripts to exact data from v1.0. But I sincerely suggest the author provide the **processed data** so that everyone can have exactly the same data.

**Comment by mmmmimic** [comment]
Thanks! How could I access the processing scripts? I tried [this](https://github.com/eccv22-ood-workshop/ROBIN-dataset/blob/master/image-classification/extract_ILSVRC.sh) but failed to find the file.
